// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmTech.Data;

#nullable disable

namespace PharmTech.Migrations
{
    [DbContext(typeof(PharmTechContext))]
    partial class PharmTechContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DispenseRecord", b =>
                {
                    b.Property<int>("DispenseRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DispenseRecordId"));

                    b.Property<DateTime>("DispensedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DispensedById")
                        .HasColumnType("int");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<int>("PrescriptionId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityDispensed")
                        .HasColumnType("int");

                    b.HasKey("DispenseRecordId");

                    b.HasIndex("DispensedById");

                    b.HasIndex("FacilityId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("DispenseRecords");
                });

            modelBuilder.Entity("DrugReturn", b =>
                {
                    b.Property<int>("ReturnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReturnId"));

                    b.Property<int>("MedId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ProcessedById")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ReturnId");

                    b.HasIndex("MedId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ProcessedById");

                    b.ToTable("DrugReturns");
                });

            modelBuilder.Entity("Facility", b =>
                {
                    b.Property<int>("FacilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FacilityId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("FacilityId");

                    b.ToTable("Facilities");
                });

            modelBuilder.Entity("InventoryItem", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InventoryId"));

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<int>("MedId")
                        .HasColumnType("int");

                    b.Property<int?>("MedicineMedId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("InventoryId");

                    b.HasIndex("FacilityId");

                    b.HasIndex("MedId");

                    b.HasIndex("MedicineMedId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("Medicine", b =>
                {
                    b.Property<int>("MedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MedId"));

                    b.Property<int>("BufferQty")
                        .HasColumnType("int");

                    b.Property<string>("DosageForm")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MedId");

                    b.ToTable("Medicines");
                });

            modelBuilder.Entity("OrderRequest", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int?>("ApprovedById")
                        .HasColumnType("int");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<int>("MedId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RequestedById")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("FacilityId");

                    b.HasIndex("MedId");

                    b.HasIndex("RequestedById");

                    b.HasIndex("SupplierId");

                    b.ToTable("OrderRequests");
                });

            modelBuilder.Entity("Prescription", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PrescriptionId"));

                    b.Property<int>("DosagePerDay")
                        .HasColumnType("int");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<int>("MedId")
                        .HasColumnType("int");

                    b.Property<int>("MedicineMedId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PrescribedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReferenceCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PrescriptionId");

                    b.HasIndex("MedicineMedId");

                    b.HasIndex("PatientId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("FacilityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.HasIndex("FacilityId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DispenseRecord", b =>
                {
                    b.HasOne("User", "DispensedBy")
                        .WithMany()
                        .HasForeignKey("DispensedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Facility", "Facility")
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prescription", "Prescription")
                        .WithMany("DispenseRecords")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DispensedBy");

                    b.Navigation("Facility");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("DrugReturn", b =>
                {
                    b.HasOne("Medicine", "Medicine")
                        .WithMany("DrugReturns")
                        .HasForeignKey("MedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("User", "Patient")
                        .WithMany("DrugReturnsAsPatient")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("User", "ProcessedBy")
                        .WithMany("DrugReturnsAsProcessor")
                        .HasForeignKey("ProcessedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Medicine");

                    b.Navigation("Patient");

                    b.Navigation("ProcessedBy");
                });

            modelBuilder.Entity("InventoryItem", b =>
                {
                    b.HasOne("Facility", "Facility")
                        .WithMany("InventoryItems")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Medicine", null)
                        .WithMany("InventoryItems")
                        .HasForeignKey("MedicineMedId");

                    b.Navigation("Facility");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("OrderRequest", b =>
                {
                    b.HasOne("User", "ApprovedBy")
                        .WithMany("OrderRequestsAsApprover")
                        .HasForeignKey("ApprovedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Facility", "Facility")
                        .WithMany("OrderRequests")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Medicine", "Medicine")
                        .WithMany("OrderRequests")
                        .HasForeignKey("MedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("User", "RequestedBy")
                        .WithMany("OrderRequestsAsRequester")
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Supplier", null)
                        .WithMany("Orders")
                        .HasForeignKey("SupplierId");

                    b.Navigation("ApprovedBy");

                    b.Navigation("Facility");

                    b.Navigation("Medicine");

                    b.Navigation("RequestedBy");
                });

            modelBuilder.Entity("Prescription", b =>
                {
                    b.HasOne("Medicine", "Medicine")
                        .WithMany("Prescriptions")
                        .HasForeignKey("MedicineMedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "Patient")
                        .WithMany("Prescriptions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.HasOne("Facility", "Facility")
                        .WithMany("Users")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("Facility", b =>
                {
                    b.Navigation("InventoryItems");

                    b.Navigation("OrderRequests");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Medicine", b =>
                {
                    b.Navigation("DrugReturns");

                    b.Navigation("InventoryItems");

                    b.Navigation("OrderRequests");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("Prescription", b =>
                {
                    b.Navigation("DispenseRecords");
                });

            modelBuilder.Entity("Supplier", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("DrugReturnsAsPatient");

                    b.Navigation("DrugReturnsAsProcessor");

                    b.Navigation("OrderRequestsAsApprover");

                    b.Navigation("OrderRequestsAsRequester");

                    b.Navigation("Prescriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
